## Pandas practice 2
범위 : transformation, groupby , visualization_timeseries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.rc('font', family='Malgun Gothic')
plt.rc('axes', unicode_minus=False)

orders = pd.DataFrame({
    '주문일자': ['2026-01-03', '2026-01-05', '2026-01-05', '2026-01-08', '2026-01-10',
             '2026-02-02', '2026-02-10', '2026-02-18', '2026-03-03', '2026-03-11'],
    '고객명': ['김철수', '이영희', '박민수', '최지영', '정다은', '홍길동', '강민호', '오세훈', '장미라', '서지수'],
    '지역': ['서울', '부산', '서울', '대전', '부산', '서울', '서울', '부산', '대전', '서울'],
    '카테고리': ['전자', '식품', '전자', '패션', '식품', '전자', '패션', '식품', '전자', '패션'],
    '상품명': ['노트북', '사과', '마우스', '자켓', '우유', '키보드', '운동화', '라면', '모니터', '가방'],
    '수량': [1, 10, 2, 1, 3, 1, 2, 5, 1, 1],
    '단가': [1500000, 3000, 25000, 120000, 2500, 50000, 90000, 4000, 350000, 70000]
})

orders['주문일자'] = pd.to_datetime(orders['주문일자'])
orders['총액'] = orders['수량'] * orders['단가']
orders

        주문일자  고객명  지역 카테고리  상품명  수량       단가       총액
0 2026-01-03  김철수  서울   전자  노트북   1  1500000  1500000
1 2026-01-05  이영희  부산   식품   사과  10     3000    30000
2 2026-01-05  박민수  서울   전자  마우스   2    25000    50000
3 2026-01-08  최지영  대전   패션   자켓   1   120000   120000
4 2026-01-10  정다은  부산   식품   우유   3     2500     7500
5 2026-02-02  홍길동  서울   전자  키보드   1    50000    50000
6 2026-02-10  강민호  서울   패션  운동화   2    90000   180000
7 2026-02-18  오세훈  부산   식품   라면   5     4000    20000
8 2026-03-03  장미라  대전   전자  모니터   1   350000   350000
9 2026-03-11  서지수  서울   패션   가방   1    70000    70000

# apply / map
1. 총액이 100000 이상이면 '고가', 아니면 '일반'을 반환하는 가격등급 열을 apply로 만드시오.
2. 지역 코드 맵을 사용해 지역코드 열을 map으로 만드시오. (서울:S, 부산:B, 대전:D)

In [3]:
def grade(x):
    if x >= 100000:
        return '고가'
    else:
        return '일반'
orders['가격등급'] = orders['총액'].apply(grade)

region_map = {'서울':'S', '부산':'B', '대전':'D'}
orders['지역코드'] = orders['지역'].map(region_map)
orders

        주문일자  고객명  지역 카테고리  상품명  수량       단가       총액 가격등급 지역코드
0 2026-01-03  김철수  서울   전자  노트북   1  1500000  1500000   고가    S
1 2026-01-05  이영희  부산   식품   사과  10     3000    30000   일반    B
2 2026-01-05  박민수  서울   전자  마우스   2    25000    50000   일반    S
3 2026-01-08  최지영  대전   패션   자켓   1   120000   120000   고가    D
4 2026-01-10  정다은  부산   식품   우유   3     2500     7500   일반    B
5 2026-02-02  홍길동  서울   전자  키보드   1    50000    50000   일반    S
6 2026-02-10  강민호  서울   패션  운동화   2    90000   180000   고가    S
7 2026-02-18  오세훈  부산   식품   라면   5     4000    20000   일반    B
8 2026-03-03  장미라  대전   전자  모니터   1   350000   350000   고가    D
9 2026-03-11  서지수  서울   패션   가방   1    70000    70000   일반    S

# 2. replace / np.where
1. 카테고리의 '식품'을 '식음료'로 바꾸시오.
2. 총액이 100000 이상이면 VIP, 아니면 NORMAL인 고객등급 열을 np.where로 만드시오.
- 주의: 이후 집계 결과에는 변경된 카테고리명(식음료)이 반영된다.

In [4]:
orders['카테고리'] = orders['카테고리'].replace({'식품':'식음료'})
orders['고객등급'] = np.where(orders['총액'] >= 100000, 'VIP', 'NORMAL')
orders

        주문일자  고객명  지역 카테고리  상품명  수량       단가       총액 가격등급 지역코드    고객등급
0 2026-01-03  김철수  서울   전자  노트북   1  1500000  1500000   고가    S     VIP
1 2026-01-05  이영희  부산  식음료   사과  10     3000    30000   일반    B  NORMAL
2 2026-01-05  박민수  서울   전자  마우스   2    25000    50000   일반    S  NORMAL
3 2026-01-08  최지영  대전   패션   자켓   1   120000   120000   고가    D     VIP
4 2026-01-10  정다은  부산  식음료   우유   3     2500     7500   일반    B  NORMAL
5 2026-02-02  홍길동  서울   전자  키보드   1    50000    50000   일반    S  NORMAL
6 2026-02-10  강민호  서울   패션  운동화   2    90000   180000   고가    S     VIP
7 2026-02-18  오세훈  부산  식음료   라면   5     4000    20000   일반    B  NORMAL
8 2026-03-03  장미라  대전   전자  모니터   1   350000   350000   고가    D     VIP
9 2026-03-11  서지수  서울   패션   가방   1    70000    70000   일반    S  NORMAL

# 3. np.select
- 총액 기준으로 주문등급 열을 만드시오.
  - 500000 이상: A
  - 100000 이상 500000 미만: B
  - 그 외: C

In [6]:
cond = [
    orders['총액'] >= 500000,
    (orders['총액'] >= 100000) & (orders['총액'] < 500000)
]
choice = ['A', 'B']
orders['주문등급'] = np.select(cond, choice, default='C')

# 4. concat
- 신규 주문 2건이 아래와 같이 들어왔다. new_orders를 orders와 세로로 연결한 result_concat을 만드시오.

- 주의:
  - 새 주문 데이터에는 아직 일부 파생 컬럼이 없을 수 있다.
  - 필요하면 orders의 컬럼 구조에 맞춰 정리한 뒤 연결해도 된다.

In [7]:
new_orders = pd.DataFrame({
    '주문일자': pd.to_datetime(['2026-03-20', '2026-03-25']),
    '고객명': ['한지민', '이도윤'],
    '지역': ['부산', '서울'],
    '카테고리': ['전자', '식음료'],
    '상품명': ['이어폰', '커피'],
    '수량': [2, 4],
    '단가': [80000, 5000],
    '총액': [160000, 20000]
})

result_concat= pd.concat([orders, new_orders])

# 5. merge
- 고객 등급표를 결합하시오. 고객명 기준으로 left join 하여 orders_grade를 만드시오.

- 확인 포인트:
  - 등급표에 없는 고객은 회원등급이 NaN으로 남는다.
  - left join이므로 orders의 행 수는 유지된다.

In [8]:
orders_grade= pd.merge(orders, new_orders, on='고객명', how='left')

# 6. pivot_table
- 지역별, 카테고리별 총액 합계를 피벗 테이블로 만드시오.
- 참고:
  - 집계 결과에 따라 값이 없는 조합은 NaN으로 보일 수 있다.